name: prepub
description: |
  Automate some release tasks and ensure a good release format.
homepage: https://noga.dev
repository: https://github.com/noga-dev/prepub
# publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  build_cli_annotations: ^2.1.0

dev_dependencies:
  # analysis
  lints: ^2.0.1

  # meta
  build_runner: ^2.3.2
  build_cli: ^2.2.1

  # test
  test: ^1.16.0
