name: prepub
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  build_cli_annotations: ^2.1.0
#   path: ^1.8.0

dev_dependencies:
  # analysis
  lints: ^2.0.0

  # meta
  build_runner: ^2.3.2
  build_cli: ^2.2.1

  # test
  test: ^1.16.0
